module.exports = [
    { from: 'Corey', date: 'April 10', name: 'Code Along', amount: 10 },
    { from: 'Corey', date: 'April 7', name: 'AirPods', amount: 200 },
    { from: 'Corey', date: 'April 9', name: 'Apple', amount: -53 },
    { from: 'Corey', date: 'April 28', name: 'Taxes', amount: 123 },
    { from: 'Gigi', date: 'April 19', name: 'One Thing', amount: 40 },
    { from: 'Gigi', date: 'April 1', name: 'Dog Food', amount: 20 },
    { from: 'Gigi', date: 'April 3', name: 'Car Wash', amount: 13 },
    { from: 'Gigi', date: 'April 8', name: 'Electric Bill', amount: 231 },
    { from: 'Tim', date: 'May 20', name: 'Groceries', amount: 30 },
    { from: 'Tim', date: 'May 20', name: 'New Light Bulbs', amount: 10 },
    { from: 'Tim', date: 'May 17', name: 'Hair Cut', amount: 25 },
    { from: 'Tim', date: 'May 17', name: 'Venmo', amount: 109 },
    { from: 'Mashu', date: 'May 19', name: 'Fruit', amount: -10 },
    { from: 'Mashu', date: 'May 19', name: 'BBQ', amount: 50 },
    { from: 'Mashu', date: 'May 27', name: 'Taxi', amount: 38 },
    { from: 'Mashu', date: 'May 27', name: 'Github', amount: 7 },
  ];